[package]
name = "activebreach"
version = "0.1.0"
edition = "2021"
license = "CC-BY-NC-4.0"
repository = "https://github.com/DutchPsycho/ActiveBreach-Engine"
description = "Syscall abstraction layer via dynamic syscall proxying with dispatcher coordination"
readme = "README.md"
keywords = ["syscall", "proxy", "ntdll", "EDR", "ActiveBreach"]
categories = ["os::windows-apis", "no-std"]
exclude = ["test/*", "target/*", ".vscode", "*.dll", "*.lib"]

[dependencies]
once_cell = "1.21.1"
rustc-hash = "2.1.1"
winapi = { version = "0.3.9", features = [
    "handleapi",
    "fileapi",
    "memoryapi",
    "errhandlingapi",
    "libloaderapi",
] }

[lib]
name = "activebreach"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = []
