use std::env;
use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

fn xorshift64(state: &mut u64) -> u64 {
    let mut x = *state;
    x ^= x << 13;
    x ^= x >> 7;
    x ^= x << 17;
    *state = x;
    x
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("time")
        .as_nanos();
    let pid = std::process::id() as u64;
    let mut state = (now as u64) ^ (pid.rotate_left(17));

    let mut key = [0u8; 16];
    for i in 0..16 {
        let v = xorshift64(&mut state);
        key[i] = (v >> ((i % 8) * 8)) as u8;
    }

    let mut key_a = [0u8; 16];
    let mut key_b = [0u8; 16];
    for i in 0..16 {
        let mask = xorshift64(&mut state) as u8;
        key_a[i] = key[i] ^ mask;
        key_b[i] = mask;
    }

    let seed = (xorshift64(&mut state) & 0xFF) as u8;

    let mut plain = [0xCCu8; 32];
    plain[0] = 0x4C;
    plain[1] = 0x8B;
    plain[2] = 0xD1;
    plain[3] = 0xB8;
    // 4..=7: ssn placeholder
    plain[8] = 0xAA ^ 0xA5;
    plain[9] = 0x55 ^ 0x50;
    plain[10] = 0xC3;

    let mut enc = [0u8; 32];
    for i in 0..32 {
        let mix = (i as u8).wrapping_mul(17).wrapping_add(seed);
        enc[i] = plain[i] ^ key[i % 16] ^ mix;
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("stub_template.rs");

    let mut s = String::new();
    s.push_str("// @generated by build.rs. Do not edit.\n");
    s.push_str("pub const STUB_TEMPLATE_ENC: [u8; 32] = [");
    for (i, b) in enc.iter().enumerate() {
        if i != 0 {
            s.push_str(", ");
        }
        s.push_str(&format!("0x{:02X}", b));
    }
    s.push_str("];\n");

    s.push_str("pub const STUB_KEY_A: [u8; 16] = [");
    for (i, b) in key_a.iter().enumerate() {
        if i != 0 {
            s.push_str(", ");
        }
        s.push_str(&format!("0x{:02X}", b));
    }
    s.push_str("];\n");

    s.push_str("pub const STUB_KEY_B: [u8; 16] = [");
    for (i, b) in key_b.iter().enumerate() {
        if i != 0 {
            s.push_str(", ");
        }
        s.push_str(&format!("0x{:02X}", b));
    }
    s.push_str("];\n");

    s.push_str(&format!("pub const STUB_SEED: u8 = 0x{:02X};\n", seed));

    fs::write(dest, s).expect("write stub_template.rs");
}
